# permissions for end users to view votingapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: votingapp-viewer-role
rules:
- apiGroups:
  - poll.vmware.com
  resources:
  - votingapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - poll.vmware.com
  resources:
  - votingapps/status
  verbs:
  - get
